math: # 数学
  title: Math
  path: topic/math.md
  detail: false
  problems:
    - 1
    - 2
    - 3
target_sum: # 目标和
  title: Target Sum
  path: topic/Target Sum.md
  detail: false
  problems:
    - 1
    - 15
    - 18
    - 167
    - 560
    - 653
palindrome: # 回文数
  title: Palindrome
  path: topic/Palindrome.md
  detail: false
  problems:
    - 5
    - 9
    - 125
    - 131
    - 234
linked_list: # 链表
  title: LinkedList
  path: topic/LinkedList.md
  detail: false
  problems:
    - 2
arithmetic: # 算术
title: Arithmetic
  path: topic/Arithmetic.md
  detail: false
  problems:
    - 2
sliding_window: # 滑动窗口
title: Sliding Window
  path: topic/Sliding Window.md
  detail: false
  problems:
    - 3
string: # 字符串
title: String
  path: topic/String.md
  detail: false
  problems:
    - 3
    - 14
sorting: # 排序
title: Sorting
  path: topic/Sorting.md
  detail: false
  problems:
    - 14
