--
-- @lc app=leetcode id=627 lang=mysql
--
-- [627] Swap Salary
--
-- https://leetcode.com/problems/swap-salary/description/
--
-- database
-- Easy (79.88%)
-- Likes:    741
-- Dislikes: 338
-- Total Accepted:    168.2K
-- Total Submissions: 210.3K
-- Testcase Example:  '{"headers":{"salary":["id","name","sex","salary"]},"rows":{"salary":[[1,"A","m",2500],[2,"B","f",1500],[3,"C","m",5500],[4,"D","f",500]]}}'
--
-- Table: Salary
-- 
-- 
-- +-------------+----------+
-- | Column Name | Type     |
-- +-------------+----------+
-- | id          | int      |
-- | name        | varchar  |
-- | sex         | ENUM     |
-- | salary      | int      |
-- +-------------+----------+
-- id is the primary key for this table.
-- The sex column is ENUM value of type ('m', 'f').
-- The table contains information about an employee.
-- 
-- 
-- 
-- 
-- Write an SQL query to swap all 'f' and 'm' values (i.e., change all 'f'
-- values to 'm' and vice versa) with a single update statement and no
-- intermediate temporary tables.
-- 
-- Note that you must write a single update statement, do not write any select
-- statement for this problem.
-- 
-- The query result format is in the following example.
-- 
-- 
-- Example 1:
-- 
-- 
-- Input: 
-- Salary table:
-- +----+------+-----+--------+
-- | id | name | sex | salary |
-- +----+------+-----+--------+
-- | 1  | A    | m   | 2500   |
-- | 2  | B    | f   | 1500   |
-- | 3  | C    | m   | 5500   |
-- | 4  | D    | f   | 500    |
-- +----+------+-----+--------+
-- Output: 
-- +----+------+-----+--------+
-- | id | name | sex | salary |
-- +----+------+-----+--------+
-- | 1  | A    | f   | 2500   |
-- | 2  | B    | m   | 1500   |
-- | 3  | C    | f   | 5500   |
-- | 4  | D    | m   | 500    |
-- +----+------+-----+--------+
-- Explanation: 
-- (1, A) and (3, C) were changed from 'm' to 'f'.
-- (2, B) and (4, D) were changed from 'f' to 'm'.
-- 
-- 
--

-- @lc code=start
-- 2022-01-07 submission
-- 8/8 cases passed
-- Runtime: 182 ms, faster than 99.51% of mysql online submissions.
-- Memory Usage: 0 MB, less than 100% of mysql online submissions.
update Salary
set sex = CHAR(ASCII('m') ^ ASCII('f') ^ ASCII(sex));
-- @lc code=end

